export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const FIND_NAME_CITY = 'FIND_NAME_CITY';
export const FIND_NAME_CITY_SUCCESS = 'FIND_NAME_CITY_SUCCESS';
export const FIND_NAME_CITY_ERROR = 'FIND_NAME_CITY_ERROR';